# -*- coding: utf-8 -*-
#
# This file is covered by the LICENSING file in the root of this project.
#

### Dockerfile for guacamole
### based on guacamole official image

FROM guacamole/guacamole

USER root

RUN mkdir -p /root/.guacamole
ADD . /root/.guacamole/

